persistence true
persistence_location /data/mosquitto/

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

allow_anonymous false

listener 1883
protocol mqtt
password_file /data/mosquitto/passwd

listener 9001
protocol websockets
password_file /data/mosquitto/passwd
