persistence true
persistence_location /data/mosquitto/

log_dest stdout
log_type error
log_type warning
log_type notice
log_type information

allow_anonymous false
password_file /data/mosquitto/passwd

# MQTT Listener
listener 1883
protocol mqtt

# WebSocket Listener
listener 9001
protocol websockets