name: "Mosquitto for HAOS ARMv7"
description: "MQTT Broker Mosquitto khusus untuk arsitektur 32-bit (Orange Pi/iHost)"
version: "1.0.2"
slug: "mosquitto_armv7"
arch:
  - armv7
startup: services
boot: auto
options:
  username: "uwaiscode"
  password: "uwaiscode"
schema:
  username: str
  password: str
ports:
  1883/tcp: 1883
  9001/tcp: 9001
