name: "Mosquitto for HAOS ARMv7"
description: "MQTT Broker Mosquitto (Standalone Mode)"
version: "1.0.3"
slug: "mosquitto_armv7"
arch:
  - armv7
startup: services
boot: auto
full_access: true
init: false
options:
  username: "uwaiscode"
  password: "uwaiscode"
schema:
  username: str
  password: str
ports:
  1883/tcp: 1883
  9001/tcp: 9001
