# Listener MQTT
listener 1883 0.0.0.0
protocol mqtt

# Listener WebSocket
listener 9001 0.0.0.0
protocol websockets

# Keamanan
allow_anonymous false
password_file /etc/mosquitto/passwd

# Logging
log_dest stdout

# Persistence
persistence true
persistence_location /var/lib/mosquitto/
