# Listener MQTT
listener 1883
protocol mqtt

# Listener WebSocket
listener 9001
protocol websockets

# Keamanan
allow_anonymous false
password_file /etc/mosquitto/passwd

# Logging
log_dest stdout

# Persistence (PASTIKAN HANYA ADA SATU BAGIAN INI)
persistence true
persistence_location /var/lib/mosquitto/
